### ISSUE TITLE
Save file gets "Corrupted" when using with Re-Reckoning

### ISSUE THREAD

**Issue by grimux** [mburbea/KoaR.AlterLevels#2]
It seems that the remastered version of KoA does not like the save files to be edited (possibly failing some type of CRC check).  I'm wondering if it would be possible to update this tool to be compatible with the remastered version.  Or even better, add this functionality to your other project, the save editor.  Being able to edit each individual zone would be an awesome feature!

The tool itself seems to still be able to find all relevant data in the save file, the game just claims "Corruption" when trying to load.

Back when I played the original game all those years ago, this type of level scaling was my biggest problem, and ultimately became the reason I never finished.  I would love for this tool to be able to work with the remaster!

**Comment by mburbea** [comment]
Yeah, this is actually entirely the issue of new crc32 checks that are more rigorously enforced. The original game had some checks against save corruption, but they get mostly ignored at the title screen.

My current priority is the save editor, and I've got a preliminary branch passing this:
https://github.com/mburbea/koar-item-editor/blob/remaster/KoAR.Core/GameSave.cs#L144-L164

If you are inclined, I'll accept a PR on this utility 😄 . 
Be warned that there is a bit of a snag, in that while the editor works now there is a chance your save file will exceed the 4mb data limit and switch over to a compressed save. I've yet to crack how that works. (I don't have any saves that large yet).

**Comment by grimux** [comment]
Okay cool!  Thanks for the info.  I want to take a look and see what I can do.  No promises though 😅

**Comment by mburbea** [comment]
Just tried it. Apparently the game recalculates the space level when you step into it. So this tool no longer works 😦
